package sshd

import (
	"bytes"
	"crypto/rand"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/crypto/ssh"

	"github.com/nokku-sh/nokkud/internal/paths"
)

// TestServerReloadPicksUpCA verifies the server can start with no cached CA
// (first boot) and, after Reload, trusts the CA that lands on disk.
func TestServerReloadPicksUpCA(t *testing.T) {
	is := assert.New(t)
	must := require.New(t)
	ca := newTestCA(t)
	configDir := t.TempDir()
	t.Setenv("NOKKUD_DATA_DIR", configDir)

	// No CA file yet: New must not fail and generates a host key into the
	// state directory.
	srv, err := New(Options{
		Principals: func(username string) []string {
			if username == currentUser(t) {
				return []string{testPrincipal}
			}
			return nil
		},
		TrustedCAs: []ssh.PublicKey{ca.pub},
	})
	must.NoError(err, "new server without CA")
	defer func() { _ = srv.Close() }()

	// Now the CA file appears (as the cert sync would write it) and Reload
	// must pick it up.
	must.NoError(os.WriteFile(
		filepath.Join(configDir, "nokku_ca.pub"),
		ssh.MarshalAuthorizedKey(ca.pub),
		0o644,
	))
	must.NoError(srv.Reload())
	is.True(srv.trustedCA(ca.pub), "reloaded server does not trust the CA that landed on disk")
}

// TestLoadTrustedCAsRetiredGrace verifies the retired CA stays trusted for
// the rollover grace window and drops off afterwards, while the active CA
// always remains trusted. With drop_retired_ca the retired CA is dropped at
// once and its file removed.
func TestLoadTrustedCAsRetiredGrace(t *testing.T) {
	is := assert.New(t)
	must := require.New(t)
	active := newTestCA(t)
	retired := newTestCA(t)
	configDir := t.TempDir()
	t.Setenv("NOKKUD_DATA_DIR", configDir)

	writeCAFile := func(name string, ca testCA) {
		t.Helper()
		must.NoError(os.WriteFile(
			filepath.Join(configDir, name),
			ssh.MarshalAuthorizedKey(ca.pub),
			0o644,
		))
	}
	trusts := func(keys []ssh.PublicKey, ca testCA) bool {
		t.Helper()
		for _, k := range keys {
			if bytes.Equal(k.Marshal(), ca.pub.Marshal()) {
				return true
			}
		}
		return false
	}

	writeCAFile("nokku_ca.pub", active)
	keys, err := loadTrustedCAs(false)
	must.NoError(err)
	is.True(trusts(keys, active), "active CA must be trusted")
	is.False(trusts(keys, retired), "no retired CA present")

	// A fresh retired CA (recent mtime) is trusted alongside the active one.
	writeCAFile("nokku_ca.previous.pub", retired)
	keys, err = loadTrustedCAs(false)
	must.NoError(err)
	is.True(trusts(keys, active), "active CA must stay trusted during the grace window")
	is.True(trusts(keys, retired), "retired CA must stay trusted during the grace window")

	// After the grace window the retired CA is no longer trusted.
	old := time.Now().Add(-retiredCAGrace - time.Hour)
	must.NoError(os.Chtimes(filepath.Join(configDir, "nokku_ca.previous.pub"), old, old))
	keys, err = loadTrustedCAs(false)
	must.NoError(err)
	is.False(trusts(keys, retired), "retired CA must stop being trusted after the grace window")
	is.True(trusts(keys, active), "active CA must remain trusted")

	// A corrupt retired CA must not break authentication.
	must.NoError(os.WriteFile(
		filepath.Join(configDir, "nokku_ca.previous.pub"),
		[]byte("garbage"),
		0o644,
	))
	keys, err = loadTrustedCAs(false)
	must.NoError(err, "corrupt retired CA must not fail the load")
	is.True(trusts(keys, active), "active CA must remain trusted with a corrupt retired CA")

	// With drop_retired_ca a fresh retired CA is not trusted, and its file is
	// removed so trust cannot come back on a later load.
	writeCAFile("nokku_ca.previous.pub", retired)
	keys, err = loadTrustedCAs(true)
	must.NoError(err)
	is.True(trusts(keys, active), "active CA must stay trusted when dropping the retired CA")
	is.False(trusts(keys, retired), "retired CA must not be trusted inside the grace window")

	_, statErr := os.Stat(filepath.Join(configDir, "nokku_ca.previous.pub"))
	is.True(os.IsNotExist(statErr), "retired CA file must be removed")

	keys, err = loadTrustedCAs(false)
	must.NoError(err)
	is.False(trusts(keys, retired), "a removed retired CA must not come back")

	// Removing an already absent file is not a failure.
	_, err = loadTrustedCAs(true)
	must.NoError(err)
}

// TestServerReloadRefreshesHostCerts verifies Reload adopts a newly written
// host certificate for the host key.
func TestServerReloadRefreshesHostCerts(t *testing.T) {
	is := assert.New(t)
	must := require.New(t)
	ca := newTestCA(t)
	configDir := t.TempDir()
	t.Setenv("NOKKUD_DATA_DIR", configDir)

	srv, err := New(Options{
		Principals: func(username string) []string {
			if username == currentUser(t) {
				return []string{testPrincipal}
			}
			return nil
		},
		TrustedCAs: []ssh.PublicKey{ca.pub},
	})
	must.NoError(err, "new server")
	defer func() { _ = srv.Close() }()

	// Read the host key generated by New, sign it as a host cert, and write
	// the cert next to it, as RenewHostCerts would.
	pubData, err := os.ReadFile(paths.HostKeyPub())
	must.NoError(err)
	hostPub, _, _, _, err := ssh.ParseAuthorizedKey(pubData)
	must.NoError(err)
	cert := &ssh.Certificate{
		Key:         hostPub,
		CertType:    ssh.HostCert,
		KeyId:       "host-test",
		ValidAfter:  0,
		ValidBefore: ssh.CertTimeInfinity,
	}
	must.NoError(cert.SignCert(rand.Reader, ca.signer))
	certPath := paths.HostKeyCert()
	must.NoError(os.WriteFile(certPath, ssh.MarshalAuthorizedKey(cert), 0o644))

	must.NoError(srv.Reload())

	// A host cert signer's PublicKey() returns the certificate itself.
	srv.certsMu.RLock()
	defer srv.certsMu.RUnlock()
	hasCert := false
	for _, signer := range srv.hostKeys {
		if c, ok := signer.PublicKey().(*ssh.Certificate); ok && c.CertType == ssh.HostCert {
			hasCert = true
		}
	}
	is.True(hasCert, "reload did not adopt the host certificate")
}

// TestParseCAFileSkipsComments verifies blank lines and comments in the CA
// file are tolerated, matching the authorized_keys format it mirrors.
func TestParseCAFileSkipsComments(t *testing.T) {
	is := assert.New(t)
	must := require.New(t)
	ca := newTestCA(t)
	path := filepath.Join(t.TempDir(), "ca.pub")

	content := "# trusted CAs\n\n" + string(ssh.MarshalAuthorizedKey(ca.pub)) + "\n# trailing comment\n"
	must.NoError(os.WriteFile(path, []byte(content), 0o644))

	keys, err := parseCAFile(path)
	must.NoError(err, "comments must not fail the parse")
	is.Len(keys, 1, "expected exactly one CA key")
	is.True(bytes.Equal(keys[0].Marshal(), ca.pub.Marshal()))
}

// TestServerReloadKeepsPreviousCAOnError verifies a CA file that becomes
// unreadable between reloads does not blank the trust set: logins keep
// working with the last known good CAs until the next successful sync.
func TestServerReloadKeepsPreviousCAOnError(t *testing.T) {
	is := assert.New(t)
	must := require.New(t)
	ca := newTestCA(t)
	configDir := t.TempDir()
	t.Setenv("NOKKUD_DATA_DIR", configDir)

	srv, err := New(Options{
		Principals: func(username string) []string {
			if username == currentUser(t) {
				return []string{testPrincipal}
			}
			return nil
		},
		TrustedCAs: []ssh.PublicKey{ca.pub},
	})
	must.NoError(err, "new server")
	defer func() { _ = srv.Close() }()

	must.NoError(os.WriteFile(
		filepath.Join(configDir, "nokku_ca.pub"),
		ssh.MarshalAuthorizedKey(ca.pub),
		0o644,
	))
	must.NoError(srv.Reload())

	// A corrupt CA file (sync raced by an editor, disk glitch, ...) must
	// leave the previous trust set in place so logins keep working.
	must.NoError(os.WriteFile(filepath.Join(configDir, "nokku_ca.pub"), []byte("garbage"), 0o644))
	_ = srv.Reload()
	is.True(srv.trustedCA(ca.pub), "previous trust set was dropped on reload error")
}
