package sshd

import (
	"bytes"
	"crypto/rand"
	"os"
	"path/filepath"
	"testing"
	"time"

	"golang.org/x/crypto/ssh"

	"github.com/nokku-sh/nokkud/internal/paths"
)

// softwareHostKeys pins the host identity to the on-disk software key so
// tests are deterministic on TPM-equipped machines.
func softwareHostKeys(p paths.Paths) func() ([]ssh.Signer, error) {
	return func() ([]ssh.Signer, error) { return loadSoftwareHostKeys(p) }
}

// TestServerReloadPicksUpCA verifies the server can start with no cached CA
// (first boot) and, after Reload, trusts the CA that lands on disk.
func TestServerReloadPicksUpCA(t *testing.T) {
	ca := newTestCA(t)
	configDir := t.TempDir()
	p := paths.Paths{ConfigDir: configDir}

	// No CA file yet: New must not fail and generates a host key into the
	// state directory.
	srv, err := New(Options{
		Paths: p,
		Principals: func(username string) ([]string, bool) {
			if username == currentUser(t) {
				return []string{testPrincipal}, true
			}
			return nil, false
		},
		TrustedCAs: []ssh.PublicKey{ca.pub},
		HostKeys:   softwareHostKeys(p),
	})
	if err != nil {
		t.Fatalf("new server without CA: %v", err)
	}
	defer func() { _ = srv.Close() }()

	// Now the CA file appears (as the cert sync would write it) and Reload
	// must pick it up.
	if err = os.WriteFile(
		filepath.Join(configDir, "nokku_ca.pub"),
		ssh.MarshalAuthorizedKey(ca.pub),
		0o644,
	); err != nil {
		t.Fatal(err)
	}
	if err = srv.Reload(); err != nil {
		t.Fatalf("reload: %v", err)
	}
	if !srv.trustedCA(ca.pub) {
		t.Fatal("reloaded server does not trust the CA that landed on disk")
	}
}

// TestLoadTrustedCAsRetiredGrace verifies the retired CA stays trusted for
// the rollover grace window and drops off afterwards, while the active CA
// always remains trusted.
func TestLoadTrustedCAsRetiredGrace(t *testing.T) {
	active := newTestCA(t)
	retired := newTestCA(t)
	configDir := t.TempDir()
	p := paths.Paths{ConfigDir: configDir}

	writeCAFile := func(name string, ca testCA) {
		t.Helper()
		if err := os.WriteFile(
			filepath.Join(configDir, name),
			ssh.MarshalAuthorizedKey(ca.pub),
			0o644,
		); err != nil {
			t.Fatal(err)
		}
	}
	trusts := func(keys []ssh.PublicKey, ca testCA) bool {
		t.Helper()
		for _, k := range keys {
			if bytes.Equal(k.Marshal(), ca.pub.Marshal()) {
				return true
			}
		}
		return false
	}

	writeCAFile("nokku_ca.pub", active)

	keys, err := loadTrustedCAs(p)
	if err != nil {
		t.Fatalf("loadTrustedCAs: %v", err)
	}
	if !trusts(keys, active) || trusts(keys, retired) {
		t.Fatal("active CA must be trusted, no retired CA present")
	}

	// A fresh retired CA (recent mtime) is trusted alongside the active one.
	writeCAFile("nokku_ca.previous.pub", retired)
	keys, err = loadTrustedCAs(p)
	if err != nil {
		t.Fatalf("loadTrustedCAs: %v", err)
	}
	if !trusts(keys, active) || !trusts(keys, retired) {
		t.Fatal("retired CA must stay trusted during the grace window")
	}

	// After the grace window the retired CA is no longer trusted.
	old := time.Now().Add(-retiredCAGrace - time.Hour)
	if err = os.Chtimes(filepath.Join(configDir, "nokku_ca.previous.pub"), old, old); err != nil {
		t.Fatal(err)
	}
	keys, err = loadTrustedCAs(p)
	if err != nil {
		t.Fatalf("loadTrustedCAs: %v", err)
	}
	if trusts(keys, retired) {
		t.Fatal("retired CA must stop being trusted after the grace window")
	}
	if !trusts(keys, active) {
		t.Fatal("active CA must remain trusted")
	}

	// A corrupt retired CA must not break authentication.
	if err = os.WriteFile(
		filepath.Join(configDir, "nokku_ca.previous.pub"),
		[]byte("garbage"),
		0o644,
	); err != nil {
		t.Fatal(err)
	}
	keys, err = loadTrustedCAs(p)
	if err != nil {
		t.Fatalf("corrupt retired CA must not fail the load: %v", err)
	}
	if !trusts(keys, active) {
		t.Fatal("active CA must remain trusted with a corrupt retired CA")
	}
}

// TestServerReloadRefreshesHostCerts verifies Reload adopts a newly written
// host certificate for the host key.
func TestServerReloadRefreshesHostCerts(t *testing.T) {
	ca := newTestCA(t)
	configDir := t.TempDir()
	p := paths.Paths{ConfigDir: configDir}

	srv, err := New(Options{
		Paths: p,
		Principals: func(username string) ([]string, bool) {
			if username == currentUser(t) {
				return []string{testPrincipal}, true
			}
			return nil, false
		},
		TrustedCAs: []ssh.PublicKey{ca.pub},
		HostKeys:   softwareHostKeys(p),
	})
	if err != nil {
		t.Fatalf("new server: %v", err)
	}
	defer func() { _ = srv.Close() }()

	// Read the host key generated by New, sign it as a host cert, and write
	// the cert next to it, as RenewHostCerts would.
	keyPath := p.SoftwareHostKey()
	keyData, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatal(err)
	}
	hostSigner, err := ssh.ParsePrivateKey(keyData)
	if err != nil {
		t.Fatal(err)
	}
	hostPub := hostSigner.PublicKey()
	cert := &ssh.Certificate{
		Key:         hostPub,
		CertType:    ssh.HostCert,
		KeyId:       "host-test",
		ValidAfter:  0,
		ValidBefore: ssh.CertTimeInfinity,
	}
	if err = cert.SignCert(rand.Reader, ca.signer); err != nil {
		t.Fatalf("sign host cert: %v", err)
	}
	certPath := keyPath + "-cert.pub"
	if err = os.WriteFile(certPath, ssh.MarshalAuthorizedKey(cert), 0o644); err != nil {
		t.Fatal(err)
	}

	if err = srv.Reload(); err != nil {
		t.Fatalf("reload: %v", err)
	}

	// A host cert signer's PublicKey() returns the certificate itself.
	srv.certsMu.RLock()
	defer srv.certsMu.RUnlock()
	hasCert := false
	for _, signer := range srv.hostKeys {
		if c, ok := signer.PublicKey().(*ssh.Certificate); ok && c.CertType == ssh.HostCert {
			hasCert = true
		}
	}
	if !hasCert {
		t.Fatal("reload did not adopt the host certificate")
	}
}
