package sshd

import (
	"crypto/rand"
	"os"
	"path/filepath"
	"testing"

	"golang.org/x/crypto/ssh"

	"github.com/nokku-sh/nokkud/internal/paths"
)

// TestServerReloadPicksUpCA verifies the server can start with no cached CA
// (first boot) and, after Reload, trusts the CA that lands on disk.
func TestServerReloadPicksUpCA(t *testing.T) {
	ca := newTestCA(t)
	configDir := t.TempDir()
	p := paths.Paths{ConfigDir: configDir}

	// No CA file yet: New must not fail and generates a host key into the
	// state directory.
	srv, err := New(Options{
		Paths: p,
		Principals: func(username string) ([]string, bool) {
			if username == currentUser(t) {
				return []string{testPrincipal}, true
			}
			return nil, false
		},
		TrustedCAs: []ssh.PublicKey{ca.pub},
	})
	if err != nil {
		t.Fatalf("new server without CA: %v", err)
	}

	// Now the CA file appears (as the cert sync would write it) and Reload
	// must pick it up.
	if err = os.WriteFile(
		filepath.Join(configDir, "nokku_ca.pub"),
		ssh.MarshalAuthorizedKey(ca.pub),
		0o644,
	); err != nil {
		t.Fatal(err)
	}
	if err = srv.Reload(); err != nil {
		t.Fatalf("reload: %v", err)
	}
	if !srv.trustedCA(ca.pub) {
		t.Fatal("reloaded server does not trust the CA that landed on disk")
	}
}

// TestServerReloadRefreshesHostCerts verifies Reload adopts a newly written
// host certificate for the host key.
func TestServerReloadRefreshesHostCerts(t *testing.T) {
	ca := newTestCA(t)
	configDir := t.TempDir()
	p := paths.Paths{ConfigDir: configDir}

	srv, err := New(Options{
		Paths: p,
		Principals: func(username string) ([]string, bool) {
			if username == currentUser(t) {
				return []string{testPrincipal}, true
			}
			return nil, false
		},
		TrustedCAs: []ssh.PublicKey{ca.pub},
	})
	if err != nil {
		t.Fatalf("new server: %v", err)
	}

	// Read the host key generated by New, sign it as a host cert, and write
	// the cert next to it, as RenewHostCerts would.
	keyPath := filepath.Join(configDir, "ssh_host_ed25519_key")
	keyData, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatal(err)
	}
	hostSigner, err := ssh.ParsePrivateKey(keyData)
	if err != nil {
		t.Fatal(err)
	}
	hostPub := hostSigner.PublicKey()
	cert := &ssh.Certificate{
		Key:         hostPub,
		CertType:    ssh.HostCert,
		KeyId:       "host-test",
		ValidAfter:  0,
		ValidBefore: ssh.CertTimeInfinity,
	}
	if err = cert.SignCert(rand.Reader, ca.signer); err != nil {
		t.Fatalf("sign host cert: %v", err)
	}
	certPath := keyPath + "-cert.pub"
	if err = os.WriteFile(certPath, ssh.MarshalAuthorizedKey(cert), 0o644); err != nil {
		t.Fatal(err)
	}

	if err = srv.Reload(); err != nil {
		t.Fatalf("reload: %v", err)
	}

	// A host cert signer's PublicKey() returns the certificate itself.
	srv.certsMu.RLock()
	defer srv.certsMu.RUnlock()
	hasCert := false
	for _, signer := range srv.hostKeys {
		if c, ok := signer.PublicKey().(*ssh.Certificate); ok && c.CertType == ssh.HostCert {
			hasCert = true
		}
	}
	if !hasCert {
		t.Fatal("reload did not adopt the host certificate")
	}
}
