name: Test

on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "buf.gen.yaml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "buf.gen.yaml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Install interop test clients
        run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

      - name: Lint and test
        run: |
          go mod tidy
          go mod verify
          go fmt ./...
          go vet ./...
          go test -race -shuffle=on -count=1 ./...

      - uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=10m

      - name: Build
        run: go build -ldflags="-s -w" -o bin/
