name: Test

on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

env:
  # renovate: datasource=github-releases depName=golangci/golangci-lint
  GOLANGCI_LINT_VERSION: v2.14.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"

      - name: Install interop test clients
        run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

      - name: Lint and test
        run: |
          go mod tidy
          go mod verify
          go fmt ./...
          go vet ./...
          go test -race -shuffle=on -count=1 ./...

      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout=10m

      - name: Build
        run: go build -ldflags="-s -w" -o bin/
